#Set up the environment to build the cc-ras-runner plugin
FROM 038611608639.dkr.ecr.us-east-1.amazonaws.com/ras6-linux-base:0.90 as builder

#names specific to artifacts downloaded from cloud-wat-resources on the HEC Nexus.  Replace version number in all args. Currently available 610,631,641. -bbb 20240229
ARG RAS_DEPLOYMENT=EngineOnly
ARG RAS_VERSION=HEC-RAS_641_Linux
ARG RAS_ARCHIVE=${RAS_VERSION}_${RAS_DEPLOYMENT}.zip
ARG NEXUS_RAS_URL=https://www.hec.usace.army.mil/nexus/repository/cloud-wat-resources/ras/${RAS_ARCHIVE}

ENV GOROOT=/go
ENV GOPATH=/src/go
ENV PATH=/go/bin:$PATH
ENV CGO_LDFLAGS="-L/hdf/lib"
ENV CGO_CFLAGS="-I/hdf/include"
ENV LD_LIBRARY_PATH=/hdf/lib


RUN wget ${NEXUS_RAS_URL} &&\ 
    unzip ${RAS_ARCHIVE} &&\
    mv /${RAS_VERSION}_${RAS_DEPLOYMENT}/libs /ras/libs &&\
    mv /${RAS_VERSION}_${RAS_DEPLOYMENT}/bin /ras/bin &&\
    chmod -R +x /ras/* &&\ 
    wget https://golang.org/dl/go1.18.1.linux-amd64.tar.gz -P / &&\
    tar -xvzf go1.18.1.linux-amd64.tar.gz -C / &&\
    mkdir -p src/ras-runner 

COPY ./ /src/ras-runner

RUN mv /src/ras-runner/runScripts/${RAS_VERSION}/* /src/ras-runner &&\
    cd /src/ras-runner 

RUN cd /src/ras-runner &&\
    go mod tidy &&\
    go build


FROM rockylinux:8 as prod

ENV PATH=/hdf/bin:/ras/bin:/ras:$PATH
ENV LD_LIBRARY_PATH=/hdf/lib

RUN mkdir -p /sim/model

COPY --from=builder /ras /ras
COPY --from=builder /src/ras-runner /ras/ras-runner
COPY --from=builder /hdf /hdf

RUN cd /ras/ras-runner &&\
    ls &&\
    mv /ras/ras-runner/run-model.sh /ras/run-model.sh &&\
    mv /ras/ras-runner/run-geom-preproc.sh /ras/run-geom-preproc.sh &&\
    chmod +x /ras/run-model.sh &&\
    chmod +x /ras/run-geom-preproc.sh

CMD ["/ras/ras-runner"]