FROM ghcr.io/usace-cloud-compute/cc-hdf5-base:latest

ENV GOROOT=/go
ENV GOPATH=/src/go
ENV PATH=/go/bin:$PATH


#names specific to artifacts downloaded from cloud-wat-resources on the HEC Nexus.  Replace version number in all args. Currently available 610,631,641. -bbb 20240229
ARG RAS_DEPLOYMENT=EngineOnly
ARG RAS_VERSION=HEC-RAS_641_Linux
ARG RAS_ARCHIVE=${RAS_VERSION}_${RAS_DEPLOYMENT}.zip
ARG NEXUS_RAS_URL=https://www.hec.usace.army.mil/nexus/repository/cloud-wat-resources/ras/${RAS_ARCHIVE}

RUN mkdir -p /ras/libs
RUN mkdir -p /ras/bin
RUN apt update &&\ 
    apt -y install git &&\
    apt -y install gcc &&\
    apt -y install make
#download RAS and put the file in the right place. Give them permissions to execute
RUN wget ${NEXUS_RAS_URL} &&\ 
    unzip ${RAS_ARCHIVE} &&\
    mv /${RAS_VERSION}_${RAS_DEPLOYMENT}/libs /ras/libs &&\
    mv /${RAS_VERSION}_${RAS_DEPLOYMENT}/bin /ras/bin &&\
    chmod -R +x /ras/* &&\
    wget https://go.dev/dl/go1.24.12.linux-amd64.tar.gz -P / &&\
    tar -xvzf go1.24.12.linux-amd64.tar.gz -C / &&\
    mkdir -p /sim/model





